//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace arkadasOnerme
{
    using System;
    using System.Collections.Generic;
    
    public partial class ogrenciProfil
    {
        public int id { get; set; }
        public Nullable<long> ogrenciNo { get; set; }
        public Nullable<int> sinema { get; set; }
        public Nullable<int> yabanciDizi { get; set; }
        public Nullable<int> yabanciMuzik { get; set; }
        public Nullable<int> halkMuzik { get; set; }
        public Nullable<int> metalMuzik { get; set; }
        public Nullable<int> futbol { get; set; }
        public Nullable<int> basketbol { get; set; }
        public Nullable<int> romanOkuma { get; set; }
        public Nullable<int> siirOkuma { get; set; }
        public Nullable<int> bilgisayarOyunu { get; set; }
        public Nullable<int> sosyalMedya { get; set; }
        public Nullable<int> sansOyunu { get; set; }
        public Nullable<int> siirYazma { get; set; }
        public Nullable<int> zekaOyunu { get; set; }
        public Nullable<int> enstrüman { get; set; }
        public Nullable<int> labels { get; set; }
    }
}
