//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace arkadasOnerme
{
    using System;
    using System.Collections.Generic;
    
    public partial class ogrenciNetwork
    {
        public int id { get; set; }
        public Nullable<long> ogrenciNo { get; set; }
        public Nullable<long> a1 { get; set; }
        public Nullable<long> a2 { get; set; }
        public Nullable<long> a3 { get; set; }
        public Nullable<long> a4 { get; set; }
        public Nullable<long> a5 { get; set; }
        public Nullable<long> a6 { get; set; }
        public Nullable<long> a7 { get; set; }
        public Nullable<long> a8 { get; set; }
        public Nullable<long> a9 { get; set; }
        public Nullable<long> a10 { get; set; }
    }
}
