//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace arkadasOnerme
{
    using System;
    using System.Collections.Generic;
    
    public partial class ogrenciAd
    {
        public int Id { get; set; }
        public Nullable<long> ogrenciNo { get; set; }
        public string ogrenciAd1 { get; set; }
    }
}
